<?php
$linkBack = "back";
$aboutMeTitle =  "about me";
$aboutMeDescription = "<p>My name is Barbora Soukupová and my main focus is in ceramics and porcelain. I like to work with concept and context, perception and interpretation. I prefer an individual approach with each part of my collection.</p><p>My current work is slightly inspired by foreign cultures, landscapes and environments. I combine my own insights and observations with the natural perception of the local people, to create a sincere description of a specific place and its nature - currently in Brazil.</p>";
$bioTitle = "bio";
$bioDescription = "<p>2005 - 2009 Hight school Náhorní, Praha, Graphic Design</p><p> 2010 - 2012 HEI UJEP, Ústí nad Labem, Design dos produtos</p><p> 2013 - 2015 HEI UJEP, Ústí nad Labem, Design de ceramica 
</p><p>2016 - HEI UJEP, Ústí nad Labem, Design de ceramica, MgA.</p><br><p> <strong>Internships: </strong><br><br>2011 - Universidade da Madeira, Madeira (PT), Design <p>2014 - Universidade do Extremo Sul Catarinense UNESC, Brasil, Visual Arts</p><p>2015 - 2016 Universidade do Etremo Sul Catarinense, UNESC, Brasil, Visual Arts.";
$contactTitle = "kontakt";
$contactDescription = "<p><strong>email:</strong> soukup.barbora@gmail.com<br><br><strong>tel:</strong> +420 774 843 300</p>";

//SOU PROJECT
$projectSouPais = "Brazil";
$projectSouTitle = "Local Project";
$projectSouTitleIntent = "intention";
$projectSouTitleRealization = "realization process";
$projectSouTitleConclusion = "conclusion";
$projectSouDescriptionIntent = "<p>LOCAL is a project primarily focused with collaboration between people from different countries, backgrounds and cultures, which through confrontation of their opinions and my observations searches for a expression of local character, identity.</p><p>I focus preferably in cooperation with communities and non-profit organisations. The intention is to create artefacts, that through its formation, can help on the composition of space for the development of intercultural communication and mutual empathy - in environments with bigger necessity for cultural actions.</p><p>The project should help to stimulate and foster positive attitudes with relations to creative activities, as well as sensitivity to the perception of nature, culture, traditions, own surroundings and way of life. </p><p>I am trying to take advantage of the integrating, activating and encouraging arts potential. The creative work here serves as a mediator, as a tool to remove social and intercultural barriers.</p>";
$projectSouDescriptionRealization = "<p>The collaboration between me and the above-mentioned subjects begins with a lecture and presentation about the Czech Republic. My intention is to demonstrate the main features and characteristics of my country, way of life, culture and thought, explaining the differences and comparing them with those from abroad, currently Brazilians.</p><p>With my presence I want to mediate to others my experience of living in other countries, associated with perception of cultural differences, and the necessity to tolerance diversity.</p><p>My goal is to motivate participants to ponder and reflect about their own environment, culture, and folklore, comparing and expressing through the artefacts, making it possible to present them to others.</p><p>The result is a combination of authentic objects reflecting on the local place through activities of its own habitants, in connection with my perceptions of a spectator from the outside - foreigner.</p><p>The project can also include lectures and demonstrations of local crafts and their production. To the involved ones, through activities I will try to show them craft process, so they can learn and eventually use them in the future. Thus, extending their manual skills and perhaps their ownsatisfaction.</p>";
$projectSouDescriptionConclusion = "<p>The result of this project will be an exhibition in the place of its execution. The event, which will symbolically culminate our cooperation and present the outcome for the public. Enabling seemingly different groups of people to get to know one another.</p><p>The second purpose of the exhibition is the sale of selected artefacts. Part of the proceeds from the sale will be directed back into the community center or organisation - more specific - to the participants.</p><p>These funds will pay the necessary costs of a small journey in the surroundings - in this case, probably nearby an outdoor museum. In my opinion, makes sense to conclude the project going on a trip associated with education. I want to a certain degree enable the joy of traveling and exploring with enthusiasm, as it was provided to me.</p>";

//SOU PROJECT 1
$projectSouNameTitle1 = "Brazil <br>and project Local n°1";
$projectSouDescription1a = "<p>No °1 is the first implementation of this project carried out in Brazil. The result is three vases, created with the help of few children from a community center in a city of southern Brazil - Timbé do Sul - SC. The vases are inspired by Brazilian traditions, crafts and beautiful nature.</p>";
$projectSouDescription1b = "<p>The Macramé handcraft products, which are a tradition in Brazil, were a major inspiration of this vase. </p><p>A solid base of vine is intertwined with cotton, whose cultivation, processing and export of Brazil‘s highly praised and infamous throughout the world.</p><p>The vase includes necklaces with stones from Araranguá river and dreamcatcher filter with bird feather, which were made by the children.</p>";
$projectSouDescription1c = "<p>Vase inspired by flowers, trees and Brazilian plants. Actually, by nature in general.</p><p>Blade of rice, tabaco and banana leafs, flowers... All collected in the gardens and fields of the children&#39;s families or brought from a trip, and finally entwined into a vine basket. Dehydrated and pressure moulded to conserve its beauty for a longer time.</p>";
$projectSouDescription1d = "<p>The third vase, inspired by Indian history and their crafts techniques.</p><p>Bird feathers, necklaces and headbands - this was our reference.</p><p>Feathers were collected in the children homes and found during walks around the neighbourhood - from the hen to the owl.</p>";
$projectSouDescription1e = "<p>The result with an autors. </p>";


//SOU PROJECT 2
$projectSouNameTitle2 = "Brazil <br>and community<br> center <br>in Timbé do Sul";
$projectSouDescription2 = "<p>The community center - a place where (in this case) children gather outside of school time - before or after school. The aim of the community center is to provide a space for children and intermediators of diverse activities. Children can study, and create their own activities, or attend Capoeira circles, computers, Zumba... The intention is to fill their free time during the day and provide them with a meaningful program to avoid spending time on the streets and its associated problems. Unfortunately, some of these children are from socially complicated environments and the community center together with regular school, becomes a fundamental pillar for their development.</p><p>Photographs document our meetings at the community center. Familiarisation, presentation, collection of materials, implementation of vases and also Capoeira night. It is a small cross-section of our common days and virtual presentation of the co-authors of vases - meet each other.</p><p>I apologize for the quality of the photos - most of them were taken by children, thereby in my opinion, make them even more authentic and perfectly describing the atmosphere of the place.</p>";

//SOU PROJECT 3
$projectSouNameTitle3 = "Southern Brazil,<br> Timbé do Sul<br> and environs";
$projectSouDescription3 = "<p>The photos in this gallery depict an environment close to the community center - a part of the state of Santa Catarina and its surroundings of Timbé do Sul city. It is a region of beautiful mountains (where temperatures in the winter fall below zero), canyons, waterfalls, rivers, flowers, rice and tobacco fields, banana and Eucalyptus alleys.</p><p>The region was originally densely populated by Indians, but unfortunately their fate is well known. Only a few tribes survived, the most famous of them are Kaingang, Guarani and Xokleng. Today it is possible to visit them and learn about their way of life and art-crafts.</p><p>Santa Catarina began to be colonised (sadly for the original tribes) in the 17th century, but South Timbé do Sul and its surrounding areas only many years later. Not until the 19th century came the first Germans and Italians, whose descendants till today make the largest part of the population. Later also came the Polish, Ukrainians and clearly the Portuguese - mostly from the Azores. And we could also find a few Czechoslovaks.</p><p>The city of Timbé do Sul was founded by Italians, whose faces can still be seen in photographs on tombstones, in the oldest local cemetery. Frequently Italian feasts are held, and in “German” cities, as an example Octoberfest. Curiously you can find cities and communities with names such as New Venice, New Rome, New Vicença and similar. Even the form of the oldest houses in the city will indicate where the great-grandparents of its residents came from.</p>";

//CANS PROJECT
$projectCansNameTitle = "The vitamin<br> is grund!";
$projectCansDescription1 = "<p>These &quot;cans&quot; are kids parodies of healthy energy drinks. Throughout its illustrations, in a funny way should encourage the consumption of fruits and vegetables, mainly of natural juices. Energy from nature, not from sugar.</p><p>The volume of one energy “drink” is 200ml, equally the recommended daily intake of fruit juices.</p><p>Long live the vitamin, hip hip!</p>";

//STONES PROJECT
$projectStonesNameTitle = "And again that stone";
$projectStonesDescription1 = "<p>These objects were created as the first record of my memories from staying on the island of Madeira, and thus became the first step to propose a collection of the island of Madeira.</p><p>It's the memory of the landscape, culture and friends, projected into &#39;stone&#39;, souvenir.</p>";

//MADEIRA PROJECT
$projectMadeiraNameTitle = "Madeira";
$projectMadeiraDescription1 = "<p>This collection is an enumeration of my memories and observations of my stay on the Madeira island and sucessor of the “stone“ memories from the island. Nature, history, architecture, traditions, culture and also personal experiences and reflections. I tried to visualize all of this in four vases and two urns/objects.</p>";
$projectMadeiraDescription2 = "<p>These two stone vases are inspired by the volcanic origin of Madeira, its shape, mountainous and Levadas - concrete channel, leading water from the mountains down into the valley, and at the same time forming the only passable paths to the mountains. Levadas as a human intervention to the appearance of the landscape.</p>";
$projectMadeiraDescription3 = "<p>Inspired by aged Madeirian architecture, crumbling stone houses, thick walls, weight and structure.</p><p>Azulejos, Portuguese blue painted tiles, applied on church and house walls with its history sometimes forgotten.</p>";
$projectMadeiraDescription4 = "<p>The vase of Flowers account the Madeira festivities. Originally live flowers, encircling the vase, are recalling the carpets of flowers that are part of the festivities which enlighten all of the capital city of Madeira - Funchal.</p><p>The painted dots - despite the white melancholy of memories - symbolise the joy and festivities of this place. In its dots you can also find a Madeirian proverb, describing the relationship between the local people and Madeira Island visitors during the festivities. At least in my opinion and personal experience.</p>";
$projectMadeiraDescription5 = "<p>Urn, which has no relation with death, but with the past - this is another part of my work. It is the memory of the people we‘ve met in the past, containing objects that reminds us of them.</p><p>Roots grow on its surface and in the interior - on the other side, is a flower from Madeira - is covered with gold leaves and fixed to the roots.</p><p>Inwards the urn - as well as to the past - we can sometimes peek and see what we cannot touch but is impossible to forget.</p>";
$projectMadeiraDescription6 = "<p>This urn is an interpretation of memories from Madeira, but also of remembering as such. This is an hourglass, which show us the passage of time.</p><p>The inside of the urn is covered with reliefs of Portuguese Azulejos and filled with black lava sand from the island. Underneath the urn is a small hole, plugged by a stone from the mountain, which represents remembrance.</p><p>When you remove the stone to remember, the sand which represents a time, begins to fall initiating its countdown. This could mean, when you remember the past for too long, at the same time you could loose your time in the present.</p>";

//WIRE PROJECT
$projectWireNameTitle = "Once upon a time";
$projectWireDescription1 = "<p>The wire craft is in its original form slowly disappearing and I decided to search for a new path.</p><p>The wire in this case serves like it served in the past - to protect the objects or connect them incase its broken - in several parts.</p><p>The individual pieces become a single object, which together, carries its memories. Are family artefacts, in its sentimentality connecting generations and its time difference.</p>";
$projectWireDescription2 = "<p>I took advantage of one of the characteristics of wire working, with objects already finished - old porcelain or ceramics, wiring them in order to protect or decorate.</p><p>That being said, I decided to work with my family artefacts. At home, I searched old objects which nobody uses anymore, despite this, we do not want to give up on them, for their historical or emocional value. I began to recycle the objects, looking for new forms. I combine and took them to Mr. Kulhánek to wire them.</p><p>These are that first two large objects. Mr. Kulhánek applied wire to its parts - in a tradicional way, and later on I, in respect to nature and shape of the objects, intuitively completed them with a coloured wire.</p><p>I was looking for a new approach to working with wires, together with antique objects, in thanks, which the wiring craft has formed.</p>";


//CONTRARY PROJECT
$projectContraryNameTitle = "Contradictions";
$projectContraryDescription1 = "<p>The intention and ambition of this collection is to demonstrate the contrast between material and form, amidst the porcelain, its characteristics and nature of the objects. Fragility and softness, sharpness and robustness.</p>";
$projectContraryDescription2 = "<p>My inspiration for the form were also two other contrasts - male and female body.</p>";
?>