<?php
$linkBack = "voltar";
$aboutMeTitle =  "sobre mim";
$aboutMeDescription = "<p>Meu nome é Barbora Soukupová e tenho foco principalmente em cerâmica e porcelana. Gosto de trabalhar com o conceito e contexto, percepção e interpretação. Prefiro uma abordagem individual a cada peça de minhas coleções.</p><p>Meu trabalho atual é levemente inspirado em culturas, paisagens e meio ambientes estrangeiros. Combino minhas próprias observações e introspecções com apercepção natural dos residentes locais, para que se possa formar uma descrição sincera danatureza do lugar determinado - atualmente do Brasil.</p>";
$bioTitle = "bio";
$bioDescription = "<p>2005 - 2009 Ensino médio Náhorní, Praha, Design Gráfico</p>
<p>2010 - 2012 UN UJEP, Ústí nad Labem, Design dos produtos </p>
<p>2013 - 2015 UN UJEP, Ústí nad Labem, Design de ceramica </p><p>2016 - UN UJEP, Ústí nad Labem, Design de ceramica, MgA.</p><br>
<p><strong>Intercambios:</strong><br><br> 2011 - Universidade da Madeira, Madeira (PT), Design</p><p> 2014 - Universidade do Extremo Sul Catarinense UNESC, Brasil, Artes Visuais</p><p>2015 - 2016 Universidade do Etremo Sul Catarinense, UNESC, Brasil, Artes Visuais</p>";
$contactTitle = "contato";
$contactDescription = "<p><strong>email:</strong> soukup.barbora@gmail.com<br><br><strong>tel:</strong> +420 774 843 300</p>";

//SOU PROJECT
$projectSouPais = "Brasil";
$projectSouTitle = "Projeto Local";
$projectSouTitleIntent = "inteção";
$projectSouTitleRealization = "processo de realização";
$projectSouTitleConclusion = "conclusão";
$projectSouDescriptionIntent = "<p>LOCAL é um projeto com foco principalmente em colaborações com pessoas de diferentes países, ambientes e culturas, que através da confrontação de suas opiniões e minhas percepções, busca expressar o caráter e identidade local.</p><p>Busco de preferência a cooperação com comunidades e organizações sem fins lucrativos. O objetivo é criar artefatos, que através de sua formação, podem ajudar na composição de espaços para o desenvolvimento da comunicação intercultural e empatia mútua - em ambientes com maior necessidade de ações culturais.</p><p>O projeto deveria ajudar na estimulação e fomentação de atitudes positivas em relação à atividades criativas, sensibilidade à percepção da natureza, cultura, tradições e meio ambiente.</p><p>Estou tentando aproveitar do potencial integrador, ativador e motivador da arte. O trabalho criativo aqui serve como um mediador, uma ferramenta para remover as barreiras sociais e interculturais.</p>";
$projectSouDescriptionRealization = "<p>A colaboração entre mim e os sujeitos mencionados acima, começa com uma palestra e apresentação sobre a República Tcheca. Minha intenção é demonstrar as características principais de meu país, modo de vida, cultura e pensamento, explicar as diferenças e comparar-las com as estrangeiras, atualmente brasileiras.</p><p>Com minha presença quero mediar para os outros a experiência de vida em outros países, ligada a percepção de diferenças culturais, e tolerância necessária às diversidades.</p><p> Minha intenção é a motivação dos participantes a ponderar e refletir sobre seu próprio ambiente, cultura e folclore, a sua comparação e expressão final através dos artefatos, de modo que será possível apresentar-los aos outros.</p><p>O resultado é uma combinação de objetos autênticos, refletindo o local através das atividades realizadas pelos próprios habitantes, em conexão com minhas percepções de espectador externo - o estrangeiro.</p><p>O projeto também pode incluir palestras e manifestações sobre o artesanato local e sua produção.Para os envolvidos, tento através das atividades mostrar os processos artesanais, para que possam aprender e eventualmente utilizar-los no futuro. Assim, estendem suas habilidades manuais e com elas talvez a sua própria satisfação.</p>";
$projectSouDescriptionConclusion = "<p>O resultado deste projeto será uma exposição no lugar de sua execução. O evento, que culminará simbolicamente a nossa cooperação e apresentará os resultados ao público. Também possibilitará para os grupos de pessoas aparentemente distantes uma aproximação.</p><p>O segundo objetivo da exposição é a venda de seletos artefatos. Parte das receitas da venda será encaminhada para o centro comunitário ou organização - mais exato - para os participantes.</p><p>Estes fundos serão para pagar os custos necessários para um pequeno passeio aos arredores - neste caso, provavelmente a um museu ao ar livre nas proximidades. Na minha opinião faz sentido concluir o projeto com uma viagem associada à educação. Eu quero, pelo menos a um certo grau possibilitar a satisfação de viajar e explorar com entusiasmo, de modo como foi oportunizado para mim.</p>";

//SOU PROJECT 1
$projectSouNameTitle1 = "Brasil <br>e projeto Local n°1";
$projectSouDescription1a = "<p>N°1 é a primeira implementação deste projecto realizado no Brasil. O resultado são três vasos, criados com a ajuda das crianças de um centro comunitário em uma cidade no sul do Brasil - Timbé do Sul - SC. Os vasos são inspirados pelas tradições brasileiras, artesanato e belíssima natureza.</p>";
$projectSouDescription1b = "<p>Os produtos de artesanato Macramé, que são uma tradição no Brasil, foram uma grande inspiração deste vaso. </p><p>Uma base sólida de cipó está entrelaçada com algodão, cujo cultivo, processamento e exportação do Brasil é altamente elogiado e infame em todo o mundo.</p><p>O vaso inclui colares com pedras do rio Araranguá e filtros dos sonhos com penas de aves, que foram feitos pelas crianças.</p>";
$projectSouDescription1c = "<p>Vaso inspirado por flores, árvores e plantas do Brasil. Na verdade, por natureza em geral. </p><p>Folhas de arroz, de tabaco, de banana e flores... Tudo colhido em jardins e campos das famílias das crianças ou trazidos de uma viagem, e finalmente, entrelaçados em cesta de cipó. Desidratado e prensado para conservar a sua beleza por mais tempo.</p>";
$projectSouDescription1d = "<p>O terceiro vaso, inspirado por histórias indígenas e suas técnicas artesanais. </p><p>Penas de pássaros, colares e testeiras - isso foi o nossa referência. A pluma foi coletada nas casas das crianças e encontrada durante caminhadas ao redor do bairro, da galinha até á coruja.</p>";
$projectSouDescription1e = "<p>O resultado com autores.</p>";

//SOU PROJECT 2
$projectSouNameTitle2 = "Brasil <br>e centro comunitário<br> em Timbé do Sul";
$projectSouDescription2 = "<p>O centro comunitário - um lugar onde (neste caso) as crianças se reúnem fora do horário escolar, ou seja, antes ou depois da escola. O objetivo do centro da comunidade é proporcionar um espaço para as crianças e os intermediários de diversas atividades. As crianças podem estudar e criar as atividades próprias, ou participar de aulas de Capoeira, computadores, Zumba... A intenção é preencher o tempo livre durante o dia, proporcionar às crianças um programa significativo e evitar o gasto de tempo nas ruas - e com isso os problemas associados. Infelizmente, algumas dessas crianças são de ambiente socialmente complicado e o centro comunitário junto com a escola tornam-se um pilar fundamental para seu desenvolvimento.</p><p>Fotografias documentam as nossas reuniões no centro comunitário. Familiarização, apresentação, coleta de materiais, implantação de vasos e também a noite de Capoeira. É um pequeno corte transversal de nossos dias comuns e apresentação virtual dos co-autores dos vasos - se conhecem. </p><p>Peço desculpa pela qualidade das fotos - a maioria delas foi registrada pelas crianças, o que na minha opinião, torna elas ainda mais autêntica e descrevem perfeitamente a atmosfera do momento.</p>";

//SOU PROJECT 3
$projectSouNameTitle3 = "Sul do Brasil,<br> Timbé do Sul<br> e arredores";
$projectSouDescription3 = '<p>As fotos nesta galeria retratam o ambiente próximo ao centro comunitário - uma parte do estado de Santa Catarina e arredores da cidade de Timbé do Sul. É uma região de bela serra (onde as temperaturas no inverno caiem até abaixo de zero), cânions, cachoeiras e rios, flores, campos de arroz e de tabaco, banana e aléias de eucaliptos.</p><p>Originalmente essa região foi povoada abundantemente por Índios, mas o que infelizmente foi o seu destino, é bem conhecido. Sobreviveram apenas algumas tribos, as mais famosas delas são Kaingang, Guarani e Xokleng. Hoje é possível visita-los e aprender sobre seu modo de vida e artesanato.</p><p>Santa Catarina começou a ser colonizada (tristemente para as tribos originais) no século XVII, mas em Timbé do Sul e arredores só muitos anos mais tarde. Só no século XIX, vieram os primeiros alemães e italianos, cujos descendentes ainda hoje fazem a maior parte da população. Além deles, mais tarde também vieram poloneses, ucranianos e, claramente, portugueses - principalmente dos Açores. Mas também encontraríamos uns tchéco-eslovacos.</p><p>A própria cidade de Timbé do Sul foi fundada por italianos, cujos rostos ainda podem ser vistos em fotografias de lápides, no cemitério mais antigo do local. Frequentemente são realizadas festas “italianas&quot;, e nas cidades alemães a festa da Octoberfest, como um exemplo. Também curiosamente podemos encontrar cidades ou comunidades com nomes como Nova Veneza, Nova Roma, Nova Vicença e similares. Até a forma das casas mais antigas das cidades indicam de onde vieram os bisavós de seus habitantes.</p>';

//CANS PROJECT
$projectCansNameTitle = "A vitamína<br> é grunnd!";
$projectCansDescription1 = "<p>Estas &quot;latas&quot; são paródias infantis das bebidas energéticas saudáveis. Ao longo de suas ilustrações deveriam de uma maneira divertida, incentivar o consumo de frutas e vegetais, e principalmente dos sucos naturais. Energia da natureza, não de açúcar.</p><p>Volume de um energético é de 200ml, igual como a ingestão diária recomendada de sucos de frutas.</p><p>Viva a vitamina, hip hip!</p>";
$projectCansDescription2 = "<p>Volume de um 'energy drink' é 200ml, mesmo como a ingestão diária recomendada de sucos de frutas.</p>";
$projectCansDescription3 = "<p>Ilustração.</p>";

//STONES PROJECT
$projectStonesNameTitle = "E de novo essa pedra";
$projectStonesDescription1 = "<p>Esses objetos foram criados como o primeiro registro de minhas memórias da estadia na ilha da Madeira. E portanto, tornaram-se os primeiros passos para propor a coleção da Ilha da Madeira. </p><p>É a memória da paisagem, da cultura e dos amigos, projetada na &quot;pedra&quot;, suvenir.</p>";
$projectStonesDescription2 = "<p>Para criar estruturas e alívios eu usei flores, agulhas das árvores, arroz, terra, impressões dos rostos - o que é para mim o mais memorizado da ilha.</p>";

//MADEIRA PROJECT
$projectMadeiraNameTitle = "Madeira";
$projectMadeiraDescription1 = "<p>Esta coleção é uma enumeração de minhas observações e lembranças da estadia na ilha da Madeira, e a sucessora das “pedras&quot; da ilha. Natureza, história, arquitetura, tradições, experiências culturais e também, as vivências e reflexões pessoais. Tudo isso tentei visualizar em quatro vasos e duas urnas/objetos.</p>";
$projectMadeiraDescription2 = "<p>Esses dois vasos das pedras são inspirados pela origem vulcânica da Madeira, sua forma, montanhas e Levadas - canal de concreto, levando a água das montanhas para o vale abaixo, e ao mesmo tempo constituindo únicos caminhos transitáveis das montanhas. Levadas como uma intervenção humana á aparência da paisagem.</p>";
$projectMadeiraDescription3 = "<p>Inspirado pela arquitetura antiga madeirense, pelas casas das pedras em desintegração, suas grossas paredes, peso e estrutura. </p><p>Azulejos portugueses pintados de azul, aplicados em paredes de igrejas e casas com histórias muitas vezes esquecidas.</p>";
$projectMadeiraDescription4 = "<p>Vaso das flores conta sobre as festas madeirenses. As flores originalmente vivas, cercando o vaso, estão relembrando os tapetes de flores que fazem parte das festividades e que iluminam toda a cidade capital da Madeira - Funchal.</p><p>Os pontos pintados - apesar da melancolia branca da lembrança - simbolizam a alegria desse lugar e de suas festas. Nos pontos também se encontra um provérbio madeirense, que descreve a relação dos madeirenses aos visitantes da ilha durante as festas. Pelo menos na minha opinião e experiências que vivi lá.</p>";

$projectMadeiraDescription5 = "<p>Urna, que não tem relação à morte, mas sim com o passado - isso é outra parte desse trabalho. É a memória das pessoas que conhecemos no passado, contendo objetos que nos lembram-lhes. </p><p>Na sua superfície crescem raízes, e em seu interior - no outro lado, há uma flor da Madeira - é coberta com folhas de ouro e fixada às raízes.</p><p>Dentro a urna podemos - bem como ao passado - espreitar e ver aquilo que não podemos tocar, mas não dá de esquecer.</p>";
$projectMadeiraDescription6 = "<p>Essa urna é uma interpretação de memórias da Madeira, e também das lembranças em si. É a ampulheta que nos mostra a passagem do tempo.</p><p>A urna por dentro está coberta com relevos de azulejos portugueses e preenchida com areia de lava da ilha. Debaixo da urna há um pequeno orifício, tampado com uma pedra das montanhas, que significa lembranças.</p><p>Quando você tira a pedra para relembrar, a areia representando o tempo, começa a vazar iniciando a sua contagem. Isso quer dizer que, quando você relembra demais o passado, ao mesmo tempo pode se perder o seu presente.</p>";

//WIRE PROJECT
$projectWireNameTitle = "Era uma vez";
$projectWireDescription1 = "<p>O artesanato de arame está em sua forma original lentamente desaparecendo, e eu decidi procurar uns novos caminhos para ele.</p><p>O fio nesse caso serve como servia no passado - para proteger os objetos ou conectar-los se fossem quebrados - até então de várias partes.</p><p>As peças individuais tornaram-se um único objeto, que junto a ele, carrega suas memórias. São artefatos da família, que em sua sentimentalidade conectam gerações e a diferença temporal.</p>";
$projectWireDescription2 = "<p>Aproveitei uma das características do trabalho de arame com objetos já acabados - porcelana ou cerâmica antiga, pronta para passar o fio com propósito de proteger ou decorá-las. </p><p>Portanto, decidi trabalhar com artefatos de minha família. Em casa eu procurei os objetos antigos, que hoje ninguém mais usa, e apesar disso não queremos desistir deles por seu valor histórico ou emocional. Comecei a reciclar os objetos e procurar novas formas para eles. Combinei-los e levei para o Sr. Kulhánek, para passar o arame.</p><p>São os primeiros dois objetos grandes. O Sr. Kulhánek passou arame nas partes deles - de maneira tradicional, e eu, em seguida, conforme a natureza e a forma do objeto, intuitivamente conclui o objeto com arame colorido.</p><p>Eu estava procurando novas abordagens para o trabalho com arame, junto aos objetos antigos, graças, quais esse artesanato se desenvolveu.</p>";



//CONTRARY PROJECT
$projectContraryNameTitle = "Contrários";
$projectContraryDescription1 = "<p>A intenção e ambição desta coleção é demonstrar o contraste entre o material e forma, assim, entre a porcelana, as suas características e natureza dos objetos. Fragilidade e suavidade, nitidez e robustez.</p>";
$projectContraryDescription2 = "<p>A minha inspiração para a forma foram também outros dois contrastes - o corpo masculino e feminino.</p>";
?>